const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
};

export default CartActionTypes;
